# This file is for local development only
# In Streamlit Community, set these in the app settings

[passwords]
admin = "$2b$12$iWXWlWvKgFrCVaWsgR2MUOtYm8ByLpUEaKJsL5V2gY9nqMjJ5b5Hy"  # password: admin123

[api_keys]
openai = ""  # Add your OpenAI API key here

[auth]
cookie_name = "career_assessment_cookie"
cookie_key = "random_signature_key_123"
cookie_expiry_days = 30
